const ActionTypes = {
  
        SET_PRODUCTS:'SET_PRODUCTS',
        SET_PRODUCTS_ONE:'SET_PRODUCTS_ONE',
        SET_PRODUCTS_TWO:'SET_PRODUCTS_TWO',
        SET_PRODUCTS_THREE:'SET_PRODUCTS_THREE',
        SET_PRODUCTS_FOUR:'SET_PRODUCTS_FOUR',
        SET_PRODUCTS_FIVE:'SET_PRODUCTS_FIVE',
        SET_PRODUCTS_SIX:'SET_PRODUCTS_SIX',
        SET_PRODUCTS_SEVEN:'SET_PRODUCTS_SEVEN',
        SET_PRODUCTS_EIGHT:'SET_PRODUCTS_EIGHT',
        SET_PRODUCTS_NINE:'SET_PRODUCTS_NINE',
        SET_PRODUCTS_TEN:'SET_PRODUCTS_TEN',
        SET_PRODUCTS_ELEVEN:'SET_PRODUCTS_ELEVEN',
        SET_PRODUCTS_TWELVE:'SET_PRODUCTS_TWELVE',
        SET_PRODUCTS_THIRTEEN:'SET_PRODUCTS_THIRTEEN',
        SET_PRODUCTS_FOURTEEN:'SET_PRODUCTS_FOURTEEN',

        SET_PRODUCTS_FIFTEEN:'SET_PRODUCTS_FIFTEEN',
        SET_PRODUCTS_SIXTEEN:'SET_PRODUCTS_SIXTEEN',
        SET_PRODUCTS_SEVENTEEN:'SET_PRODUCTS_SEVENTEEN',
        SET_PRODUCTS_EIGHTEEN:'SET_PRODUCTS_EIGHTEEN',
        SET_PRODUCTS_NINTEEN:'SET_PRODUCTS_NINTEEN',
        SET_PRODUCTS_TWENTY:'SET_PRODUCTS_TWENTY',

        SELECTED_PRODUCTS:'SELECTED_PRODUCTS',
        REMOVE_SELECTED_PRODUCTS:'REMOVE_SELECTED_PRODUCTS'
}
export default ActionTypes